sudo: required

language: php
php:
  - '7.1.9'

branches:
  only:
    - master

# travis runtime environment from here or settings. : https://docs.travis-ci.com/user/environment-variables/
env:
  global:
    - ZIP_FILE="on-premises-$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT.zip"
#    - AWS_ACCESS_KEY_ID=""
    - secure: "BzDzI+IzBppUze4m43LK7vy+leULLemF0W58QbNAoKaVjjRwfziCgKKngFkEBwTdy4pYcOc8VIf2aXbYC73OJ89aFmdXtKHOwggnxpMUicR/57j9WKRdXonX6BYMEXxKESh+14swBc5/NVzoDFchJEaBb1s6oirzemrhWSgAbGqrUcZjbFoLewdGib/Ff1NBfWuROXmeiJzHx159tAMPkl00rrSfCBaeYcrwyHsoegZwgOyJkgKjHoG/1Bu8TjSrnr1u11ooUoIEkZ2HJATp5zPiaQyhe17v0x222d610LeRXW/IzQNeDx1VVXYkAQOIoWMZSGd4Fu73BmCWiEaJcmWee2BKKzYXOYdgrULONRZ1eczZLDs+5QGNcRDS0C07mRL5G50kfVklU7zV27QfqTv/6E+xEBieuaVTDHaLmDWZyBuOPsH+FUKplq/cCUTkyT/NoELfg4AF7ZuG4suZOEaVLZeeTylKy1b5RbMJPAknEGoOcVm+7PaaoW//EZeHhuuKYTvWd45fy+UvgzXr/Hi2Y+Z5s7RkB7gNpO7Y9PQcJUWD9IoCzATAlgn7ITiztGLVU9KQuInR3du+FqoOxDP+NO1HMWguHJdixCEW6D5zKzSjGmK1RmigGU5Hv8jRzL9SLdokEFCMyafz2czVd10dXZD0KPXC7FqsvSnrujI="
    #    - AWS_SECRET_ACCESS_KEY=""
    - secure: "rxAR2uJruqt/MyBnIPhGJS1KfGTxEStz7v5CmKocdnGXJkFQCT6DrFaWN/FMZl86x3BnKni7Lp7jjUPm4jBR1zizXU3gxx97aw2HmiK3lNksy7752LKItoIt1Zs326ldt17iNC1O6gQ0Xf7Kgk6HS/e4Xvh32BBq0LwxkWrHFWEMVc1/QdafbepyUuhEZMzoF4Or9zgzB73zSU5MMv7QbYNXd0Nrpn6F+PwlsEVPmStQNSUNFofm62B16240EwXPjnd26WLL9Fxk3lgFLyTh44HfPiUfFBFVCyUY9fZewb0TxhHw6N0Nswl90+CeXdL55glC0JRm5Y+6AL4c3XF3qZw0nMukOfCIbFz8EZ9BepiGFriSPzck/CaYz5zq74ckU372RFibYmQoTt9SvHvWnAejNwnnZtgfw7TxW8cMKuIieq3t5TNRKEIqvFGR+e7jb5PHL8WY5WpSMIx2E7fKF8ibtHkFUmHB53KvM+kEp+oOwMczG9e4ltA5dv251BNEo75bkzUzj7J4diCFAg9Ny4gkZzMHgCQFMa9ws3mMRVnwUy+8ZnztS4W5g3ocUcYsuGFt5WD9sVcC3lO4jMIo1VvXlN4cj7AOCvMuz8fUyFHGZxJMJndhV3Xo48O+75TpztA7VYt12OHJDn4sCExzngsC0Y5aUiMY9JVDeyUdbPQ="
    - AWS_REGION="ap-northeast-1"
    - CODEDEPLOY_APP="demo"
    - CODEDEPLOY_GROUP="on-premises"
    - S3_BUCKET="noah-deploy"
    - S3_FOLDER="on-premises"


# notification - https://docs.travis-ci.com/user/notifications
# notifications:
#   email:
#     recipients:
#       - one@example.com
#       - other@example.com
#     on_success: never # default: change
#     on_failure: always # default: always
notifications:
  email:
    on_failure: always
    on_success: never
    slack:
      secure: "KVXwfrsBTrU2o8KfrehmCEtlrLo71ZLkEbaJ4VjivJbTNE3GmVkTCVp6cypnDOcaHaCIDnX/1lnPsgSiaMJAA/T5hcHcE4KpZH1RlxQzO5IoSvGFZnJGq9Ebv74BfC2OjFU2af6q2i7UqNwnDroJm0OhxgqgYec2wJVMdKDJL5t39HNtFs7vunZO5mmYVPvlBRxldXmTtR+T9bhwUCWZarKDH/dz6ezp63RNR9olkorlrkf2Y7PeOSj/Fq/Qqow2/nMfLVsxbP+kqAFlGVD0TY9PWO1kYTGxRHA7sJ+D4C59toUaXCF24XgSYb3CICSKo3anxxbext5gKzjiwBueliUmvn1fgTKWTz05lofA9n81bZ7qS0OjHCY4odPUGk9EP0n4F/xAIRpGV0DW3k3w7ED/sqPnUBxFjTkteaNoJ+a5wdIEhHreMwbTxOAOY6fDOkz/YJBK5sHU2jofqTsdI660CLM4eoByLQnW3hxW16JWiMToL5JoC4buO4Fx2EcUjxAKXtcX4uQ0ddNH8WZHrsiHqJVZfI3km56cP1+4wgE3xgFbrRUyp6NmbGoFk4CqJUtdOfHXDPf1jWPkZ2r3DyOP+mRW9/i7FX8j67OMAZMZXO2oPPFNYzxgxEwGVBMt3+jTyUarBwZ6AypMn0b96sv9KNbhqaWaBiHA1g0H7R4="

  # slack:
  #   rooms:
  #     - ${SLACK_ACCOUNT}:${SLACK_TOKEN}#${SLACK_CHANNEL}"
  #   template:
  #     - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"


cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache

# build lifecycle - https://docs.travis-ci.com/user/customizing-the-build/
# (OPTIONAL) Install apt addons
# (OPTIONAL) Install cache components
# before_install
# install
# before_script
# script
# (OPTIONAL) before_cache (for cleaning up cache)
# after_success or after_failure
# (OPTIONAL) before_deploy
# (OPTIONAL) deploy
# (OPTIONAL) after_deploy
# after_script

# set -e : when error stop build.
before_install:
  - set -e


# put testing scripts here
script:
  - echo 'script step...'

before_deploy:
  - cd "$TRAVIS_BUILD_DIR";
    mkdir "$TRAVIS_BUILD_DIR/zip";
    zip -r "$TRAVIS_BUILD_DIR/zip/$ZIP_FILE" *


deploy:
  - provider: S3
    access_key_id: &aws_access_key $AWS_ACCESS_KEY_ID
    secret_access_key: &aws_secret_key
      secure: $AWS_SECRET_ACCESS_KEY
#    access_key_id: "$AWS_ACCESS_KEY_ID"
#    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    region: "$AWS_REGION"
    local_dir: "$TRAVIS_BUILD_DIR/zip"
    bucket: "$S3_BUCKET"
    upload-dir: "$S3_FOLDER"
    skip_cleanup: true
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: *aws_access_key
    secret_access_key: *aws_secret_key
#    access_key_id: "$AWS_ACCESS_KEY_ID"
#    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    region: "$AWS_REGION"
    bucket: "$S3_BUCKET"
    key: "$S3_FOLDER/$ZIP_FILE"
    bundle_type: zip
    application: "$CODEDEPLOY_APP"
    deployment_group: "$CODEDEPLOY_GROUP"
    wait-until-deployed: true
    on:
      all_branches: true
