version: 0.0
os: linux
files:
  - source: src
    destination: /var/www/html

# permissions:
#   - object: /opt/tomcat/bin
#     pattern: "*.sh"
#     owner: root
#     group: root
#     mode: 755
#     type:
#       - file

hooks:
  ApplicationStop:
    - location: script/stop-service.sh
      timeout: 180
      runas: root

  BeforeInstall:
    - location: script/earse-application.sh
      timeout: 120
      runas: root

  # AfterInstall:

  ApplicationStart:
    - location: script/start-service.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: script/verify-service.sh
      timeout: 60
      runas: root
